
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.180.93.206:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-devit-user.copkmnpqtze8.ap-northeast-2.rds.amazonaws.com:3306/devit_user?characterEncoding=utf8
    username: daehee
    password: 12345678

  rabbitmq:
    host: 52.79.236.81
    password: 1234
    port: 5672
    username: devit
    routingkey: devit.routingkey
    user :
      exchange: x.devit.user
      queue: q.devit.user
    board :
      exchange: x.devit.board
      queue: q.devit.board

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

